# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ZGOPAL
email: hello@zgopal.com
description: Bengali . Wedding . Cards
baseurl: "/zgopal.pages" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.png
font-awesome-icon-logo:

# Social settings
github_username: andrewbanchich
twitter_username: andrewbanchich
facebook_URL: andrewbanchich
instagram_username: andrewbanchich
dribbble_username: andrewbanchich
500px_username: andrewbanchich
phone: 555-5555

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
