# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TomorrowScale Institute - Towards Discovery
email: vision@tomorrowscale.org
form_id: xdoykbzd
description: The TomorrowScale Institute is a private non-profit research institute for translational science and biomedical research.
baseurl: "/phantom-jekyll-theme" # the subpath of your site, e.g. /blog
url: "tomorrowscale.org" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo:

# Social settings
github_username: tomorrowscale
twitter_username: tomorrowscale

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
