# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phantom
email: youremailaddress@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Jekyll version of the "Phantom" theme by HTML5 UP.
baseurl: "/Phantom-Jekyll-Theme" # the subpath of your site, e.g. /blog
url: "https://andrewbanchich.github.io/" # the base hostname & protocol for your site
github_username: andrewbanchich
twitter_username: andrewbanchich

# Build settings
markdown: kramdown
